### ISSUE TITLE
How to get the LIFULL HOME’S dataset?

### ISSUE THREAD

**Issue by lzd1** [zlzeng/DeepFloorplan#2]
Hi,

When I browsed the official website of the LIFULL HOME’S dataset, I found that there is only a Japanese application form, so you also filled out this application form to get this dataset?

Thanks,

Zhengda Lu

**Comment by tj-cf** [comment]
Hi Zhengda Lu,
I saw your comment about the LIFULL HOME’S dataset application form being only in Japanese. Have you found a way to resolve this issue and successfully obtain the dataset? If so, could you share how you managed to do it?
Best regards,
FC

**Comment by abner2015** [comment]
http://pan.baidu.com/s/1hqGbyQS

**Comment by tj-cf** [comment]
> http://pan.baidu.com/s/1hqGbyQS

Thank you for sharing the link. It seems that the link is no longer valid. Could you please provide an updated one? I really appreciate your help.
